service: sok-eve
package:
  individually: true

provider:
  name: aws
  region: eu-west-1
  memorySize: 3000
  timeout: 30

functions:
  htmlendpoint:
    handler:  main.handler
    runtime: nodejs8.10
    package:
      artifact: target/lambda.zip
    events:
      - http:
          path: test
          method: get

